const KEY='twoBrokeGirlsV1';
const ACCOUNTS=[
 {id:'a-cash',owner:'A',name:'Cash'},{id:'a-cashapp',owner:'A',name:'Cash App'},{id:'a-paypal',owner:'A',name:'PayPal'},
 {id:'k-cashapp',owner:'K',name:'Cash App'},{id:'k-paypal',owner:'K',name:'PayPal'},{id:'k-cash',owner:'K',name:'Cash'}
];
const ENVELOPES=[
 {id:'a-envelope',owner:'A',name:'A — Cash'},{id:'k-envelope',owner:'K',name:'K — Cash'},
 {id:'business',owner:'Shared',name:'Business'},{id:'household',owner:'Shared',name:'Household'},{id:'unsorted',owner:'Shared',name:'Unsorted'}
];
const fresh=()=>({accounts:Object.fromEntries(ACCOUNTS.map(x=>[x.id,0])),envelopes:Object.fromEntries(ENVELOPES.map(x=>[x.id,0])),activity:[],view:'home'});
let state=load();
function load(){try{return {...fresh(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return fresh()}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n)||0);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const account=id=>ACCOUNTS.find(x=>x.id===id);
const envelope=id=>ENVELOPES.find(x=>x.id===id);
const total=o=>Object.values(o).reduce((a,b)=>a+Number(b||0),0);
function ownerName(o){return o==='A'?'Amanda':o==='K'?'Katie':'Shared'}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function addActivity(x){state.activity.unshift({id:uid(),date:new Date().toISOString(),...x})}
function render(){document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));const views={home:homeView,money:moneyView,calculator:calculatorView,activity:activityView};document.querySelector('#app').innerHTML=(views[state.view]||homeView)();bind()}
function homeView(){const aTotal=ACCOUNTS.filter(x=>x.owner==='A').reduce((s,x)=>s+state.accounts[x.id],0);const kTotal=ACCOUNTS.filter(x=>x.owner==='K').reduce((s,x)=>s+state.accounts[x.id],0);return `
 <section class="hero"><p class="hero-label">All money across every account</p><div class="hero-value">${money(total(state.accounts))}</div><p>Amanda ${money(aTotal)} · Katie ${money(kTotal)}</p></section>
 <div class="quick"><button class="btn primary" data-open="income">Add money</button><button class="btn" data-open="move">Move money</button><button class="btn" data-go="calculator">Use split calculator</button></div>
 <div class="section-head"><div><p>Purpose</p><h2>Envelope totals</h2></div><p>What the money is for</p></div>
 <section class="grid">${ENVELOPES.map(x=>`<article class="card"><div class="card-top"><h3>${esc(x.name)}</h3><span class="tag ${x.owner.toLowerCase()}">${ownerName(x.owner)}</span></div><p class="amount">${money(state.envelopes[x.id])}</p></article>`).join('')}</section>
 <div class="section-head"><div><p>Location</p><h2>Physical accounts</h2></div><p>Where the money sits</p></div>
 <section class="account-columns"><div class="account-list">${accountGroup('A')}</div><div class="account-list">${accountGroup('K')}</div></section>`}
function accountGroup(owner){return ACCOUNTS.filter(x=>x.owner===owner).map(x=>`<article class="row-card"><div><span class="tag ${owner.toLowerCase()}">${ownerName(owner)}</span><h3>${esc(x.name)}</h3></div><strong>${money(state.accounts[x.id])}</strong></article>`).join('')}
function moneyView(){return `<div class="page-title"><h2>Update money</h2><p>Every change creates a clear activity record.</p></div><section class="action-stack">
 ${action('income','＋','Add money','Record income or an opening balance.')}
 ${action('expense','−','Record spending','Reduce an account and an envelope.')}
 ${action('move','↔','Move money','Move accounts, envelopes, or both together.')}
 ${action('adjust','✎','Correct a balance','Make a labeled correction without hiding it.')}
 </section>`}
function action(id,icon,title,text){return `<button class="action-card" data-open="${id}"><div><h3>${icon} &nbsp;${title}</h3><p>${text}</p></div><span class="arrow">›</span></button>`}
function calculatorView(){return `<div class="page-title"><h2>Split calculator</h2><p>Plan the split without changing any balances.</p></div><section class="card calc"><label class="label" for="calcAmount">Amount to divide</label><div class="money-input"><span>$</span><input id="calcAmount" inputmode="decimal" placeholder="100.00" aria-label="Amount to divide"></div><div id="breakdown" class="breakdown">${breakdown(0)}</div><div class="form-actions"><button class="btn" id="resetCalc">Reset</button><button class="btn primary" id="copyCalc">Copy breakdown</button></div></section>`}
function breakdown(n){const parts=[['Business',.5],['Amanda',.15],['Katie',.15],['Household',.2]];return parts.map(([name,p])=>`<div class="split-row"><div><b>${name}</b><p>${p*100}%</p></div><strong>${money(n*p)}</strong></div>`).join('')+`<div class="split-row total-row"><b>Total</b><strong>${money(n)}</strong></div>`}
function activityView(){return `<div class="page-title"><h2>Activity</h2><p>Your complete money record.</p></div><div class="filters"><select id="personFilter" aria-label="Filter by person"><option value="all">Everyone</option><option value="A">Amanda</option><option value="K">Katie</option><option value="Shared">Shared</option></select><select id="envelopeFilter" aria-label="Filter by envelope"><option value="all">All envelopes</option>${ENVELOPES.map(x=>`<option value="${x.id}">${x.name}</option>`).join('')}</select><select id="typeFilter" aria-label="Filter by type"><option value="all">All activity</option><option value="income">Money added</option><option value="expense">Spending</option><option value="account-transfer">Account moves</option><option value="envelope-transfer">Envelope moves</option><option value="combined-transfer">Combined moves</option><option value="adjustment">Corrections</option></select></div><section id="activityList" class="activity-list">${activityRows(state.activity)}</section>`}
function activityRows(items){if(!items.length)return `<div class="card empty">No activity yet. Your first money update will appear here.</div>`;return items.map(x=>`<article class="row-card activity-item"><div class="activity-icon">${x.type==='income'?'+':x.type==='expense'?'−':x.type==='adjustment'?'✎':'↔'}</div><div class="activity-meta"><h3>${esc(x.title)}</h3><p>${new Date(x.date).toLocaleString()}${x.note?' · '+esc(x.note):''}</p></div><div class="activity-money"><strong>${money(x.amount)}</strong><small>${ownerName(x.person)}</small></div></article>`).join('')}
function options(list,kind){return list.map(x=>`<option value="${x.id}">${kind==='account'?ownerName(x.owner)+' — '+x.name:x.name}</option>`).join('')}
function openModal(type){const root=document.querySelector('#modalRoot');let body='';let title='';
 if(type==='income'){title='Add money';body=`${field('person','Who received it?',`<select name="person"><option value="A">Amanda</option><option value="K">Katie</option><option value="Shared">Shared</option></select>`)}${field('account','Physical account',`<select name="account">${options(ACCOUNTS,'account')}</select>`)}${field('envelope','Envelope',`<select name="envelope"><option value="unsorted">Unsorted</option>${options(ENVELOPES.filter(x=>x.id!=='unsorted'),'envelope')}</select>`)}${amountField()}${noteField('Income source or note')}`}
 if(type==='expense'){title='Record spending';body=`${field('person','Who spent it?',`<select name="person"><option value="A">Amanda</option><option value="K">Katie</option><option value="Shared">Shared</option></select>`)}${field('account','Paid from account',`<select name="account">${options(ACCOUNTS,'account')}</select>`)}${field('envelope','Paid from envelope',`<select name="envelope">${options(ENVELOPES,'envelope')}</select>`)}${amountField()}${noteField('What was purchased?')}`}
 if(type==='move'){title='Move money';body=`${field('moveType','What should change?',`<select name="moveType" id="moveType"><option value="account-transfer">Physical accounts only</option><option value="envelope-transfer">Envelopes only</option><option value="combined-transfer">Accounts and envelopes together</option></select>`)}<div id="moveFields"></div>${amountField()}${noteField('Transfer note')}`}
 if(type==='adjust'){title='Correct a balance';body=`${field('targetType','Balance type',`<select name="targetType" id="targetType"><option value="account">Physical account</option><option value="envelope">Envelope</option></select>`)}<div id="targetField">${field('target','Account',`<select name="target">${options(ACCOUNTS,'account')}</select>`)}</div>${field('direction','Correction',`<select name="direction"><option value="add">Add to balance</option><option value="subtract">Subtract from balance</option></select>`)}${amountField()}${noteField('Reason for correction')}`}
 root.innerHTML=`<div class="modal-wrap" data-dismiss><section class="modal" role="dialog" aria-modal="true"><div class="modal-head"><h2>${title}</h2><button class="close" data-close aria-label="Close">×</button></div><form class="form" id="moneyForm" data-type="${type}">${body}<div class="form-actions"><button type="button" class="btn" data-close>Cancel</button><button class="btn primary">Save activity</button></div></form></section></div>`;
 root.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>root.innerHTML='');root.querySelector('[data-dismiss]').onclick=e=>{if(e.target===e.currentTarget)root.innerHTML=''};
 if(type==='move'){document.querySelector('#moveType').onchange=renderMoveFields;renderMoveFields()}
 if(type==='adjust'){document.querySelector('#targetType').onchange=renderTargetField}
 document.querySelector('#moneyForm').onsubmit=submitMoney}
function field(name,label,control){return `<div class="field"><label>${label}</label>${control}</div>`}
function amountField(){return field('amount','Amount','<input name="amount" type="number" min="0.01" step="0.01" inputmode="decimal" required placeholder="0.00">')}
function noteField(label){return field('note',label,`<input name="note" maxlength="120" placeholder="Optional">`)}
function renderMoveFields(){const t=document.querySelector('#moveType').value;let h='';if(t!=='envelope-transfer')h+=field('fromAccount','From account',`<select name="fromAccount">${options(ACCOUNTS,'account')}</select>`)+field('toAccount','To account',`<select name="toAccount">${options(ACCOUNTS,'account')}</select>`);if(t!=='account-transfer')h+=field('fromEnvelope','From envelope',`<select name="fromEnvelope">${options(ENVELOPES,'envelope')}</select>`)+field('toEnvelope','To envelope',`<select name="toEnvelope">${options(ENVELOPES,'envelope')}</select>`);document.querySelector('#moveFields').innerHTML=h}
function renderTargetField(){const t=document.querySelector('#targetType').value;document.querySelector('#targetField').innerHTML=field('target',t==='account'?'Account':'Envelope',`<select name="target">${options(t==='account'?ACCOUNTS:ENVELOPES,t)}</select>`)}
function submitMoney(e){e.preventDefault();const f=new FormData(e.currentTarget),type=e.currentTarget.dataset.type,amount=Number(f.get('amount'));if(!(amount>0))return toast('Enter an amount greater than zero');const note=f.get('note')||'';
 if(type==='income'||type==='expense'){const sign=type==='income'?1:-1,a=f.get('account'),v=f.get('envelope'),person=f.get('person');state.accounts[a]+=sign*amount;state.envelopes[v]+=sign*amount;addActivity({type,amount:sign*amount,person,envelope:v,title:type==='income'?`Added to ${account(a).name} + ${envelope(v).name}`:`Spent from ${account(a).name} + ${envelope(v).name}`,note})}
 if(type==='move'){const mt=f.get('moveType');let person='Shared',envId=null,title='Money moved';if(mt!=='envelope-transfer'){const from=f.get('fromAccount'),to=f.get('toAccount');if(from===to)return toast('Choose two different accounts');state.accounts[from]-=amount;state.accounts[to]+=amount;person=account(to).owner;title=`${account(from).owner} ${account(from).name} → ${account(to).owner} ${account(to).name}`}
  if(mt!=='account-transfer'){const from=f.get('fromEnvelope'),to=f.get('toEnvelope');if(from===to)return toast('Choose two different envelopes');state.envelopes[from]-=amount;state.envelopes[to]+=amount;envId=to;person=envelope(to).owner;title=mt==='envelope-transfer'?`${envelope(from).name} → ${envelope(to).name}`:title+` · ${envelope(from).name} → ${envelope(to).name}`}
  addActivity({type:mt,amount,person,envelope:envId,title,note})}
 if(type==='adjust'){const kind=f.get('targetType'),id=f.get('target'),sign=f.get('direction')==='add'?1:-1,owner=kind==='account'?account(id).owner:envelope(id).owner;state[kind==='account'?'accounts':'envelopes'][id]+=sign*amount;addActivity({type:'adjustment',amount:sign*amount,person:owner,envelope:kind==='envelope'?id:null,title:`Corrected ${kind==='account'?account(id).name:envelope(id).name}`,note})}
 save();document.querySelector('#modalRoot').innerHTML='';render();toast('Activity saved')}
function settings(){document.querySelector('#modalRoot').innerHTML=`<div class="modal-wrap" data-dismiss><section class="modal"><div class="modal-head"><h2>Settings & backup</h2><button class="close" data-close>×</button></div><div class="settings-actions"><button class="btn primary" id="exportBtn">Download backup</button><label class="btn file-label">Restore backup<input type="file" id="importFile" accept="application/json"></label><button class="btn danger" id="resetAll">Erase all app data</button></div><p class="label" style="margin-top:16px">Version 1 · Data currently saves on this device.</p></section></div>`;const root=document.querySelector('#modalRoot');root.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>root.innerHTML='');document.querySelector('#exportBtn').onclick=exportData;document.querySelector('#importFile').onchange=importData;document.querySelector('#resetAll').onclick=resetAll}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`2-broke-girls-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
function importData(e){const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!d.accounts||!d.envelopes||!Array.isArray(d.activity))throw 0;state={...fresh(),...d};save();document.querySelector('#modalRoot').innerHTML='';render();toast('Backup restored')}catch{toast('That backup file is not valid')}};r.readAsText(file)}
function resetAll(){if(confirm('Erase every balance and activity record on this device?')){state=fresh();save();document.querySelector('#modalRoot').innerHTML='';render();toast('App data erased')}}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;save();render()});document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{state.view=b.dataset.go;save();render()});document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openModal(b.dataset.open));document.querySelector('#menuBtn').onclick=settings;
 const calc=document.querySelector('#calcAmount');if(calc){calc.oninput=()=>document.querySelector('#breakdown').innerHTML=breakdown(Number(calc.value));document.querySelector('#resetCalc').onclick=()=>{calc.value='';calc.dispatchEvent(new Event('input'));calc.focus()};document.querySelector('#copyCalc').onclick=()=>{const n=Number(calc.value);if(!n)return toast('Enter an amount first');const text=`2 Broke Girls split for ${money(n)}\nBusiness 50%: ${money(n*.5)}\nAmanda 15%: ${money(n*.15)}\nKatie 15%: ${money(n*.15)}\nHousehold 20%: ${money(n*.2)}`;navigator.clipboard?.writeText(text).then(()=>toast('Breakdown copied')).catch(()=>toast('Copy is not available'))}}
 const filters=['personFilter','envelopeFilter','typeFilter'].map(id=>document.querySelector('#'+id));if(filters[0])filters.forEach(x=>x.onchange=()=>{const [p,v,t]=filters.map(y=>y.value);const items=state.activity.filter(x=>(p==='all'||x.person===p)&&(v==='all'||x.envelope===v)&&(t==='all'||x.type===t));document.querySelector('#activityList').innerHTML=activityRows(items)})}
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'));
render();